name: Build on PR

on: 
  workflow_dispatch: 
  
  pull_request:
    branches:
      - main
    
    types: [labeled]

jobs:
  build:
    if: github.event.label.name == 'run-build'  # Run only if 'run-build' label is added
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install

      - name: Init prisma
        run: npm run db:generate

      - name: Run build
        run: npm run build